/* eslint-disable */
// prettier-ignore
import Vue from 'https://cdn.jsdelivr.net/npm/vue@2.6.12/dist/vue.esm.browser.js';

const Home = Vue.component("Home", {template: ` <div class="home"> <img id="vnoLogo" src="/assets/vnoLogo.png" /> <h1>A Vue / Deno Adapter</h1> <br /> <h3> For github documentation:<br /> <a class="docTags" href="https://github.com/oslabs-beta/vno" target="_blank" rel="noopener" >&nbsp;vno documentation</a >. </h3> <h3>Installed CLI Plugin</h3> <ul> <li> <a class="docTags" href="https://github.com/oslabs-beta/vno/tree/main/command-line" target="_blank" rel="noopener" >Click Here</a > </li> <br /> </ul> </div>`, name: 'Home', props: { msg: String, },});
const Team = Vue.component("name", {template: ` <div id="team"> <img :src="picture" alt="image" border="0" width="450" height="450" /> <h2>{{ name }}</h2> <h2>{{ email }}</h2> <h2> About: <br /> {{ about }} </h2> <h2>{{ linkedIn }}</h2> <h2>{{ github }}</h2> </div>`, props: ['name', 'email', 'github', 'linkdIn', 'about', 'picture'], name: 'Team',});
const Docs = Vue.component("docs", {template: ` <div id="docs"> <h1>Docs Page</h1> </div>`, name: 'docs',});
const Demo = Vue.component("Demo", {template: ` <div id="demo"> <h1>Demo Page</h1> </div>`, name: 'Demo',});
const App = new Vue({template: ` <div id="app"> <header> <img id="gitLogo" src="/assets/git-logo.png" /> <img id="denoLogo" src="/assets/deno-logo.png" /> <ul> <a @click="handelClick('Home')"><li>Home</li></a> <a @click="handelClick('Team')"><li>Team</li></a> <a @click="handelClick('Demo')"><li>Demo</li></a> <a @click="handelClick('Docs')"><li>Docs</li></a> </ul> </header> <body v-if="displayedComponent === 'Home'"> <Home /> </body> <body v-else-if="displayedComponent === 'Team'"> <Team v-for="person in team" :key="person.id" :name="person.name" :about="person.about" :picture="person.picture" :email="person.email" :github="person.github" :linkdIn="person.linkdIn" /> </body> <body v-else-if="displayedComponent === 'Docs'"> <Docs /> </body> <body v-else-if="displayedComponent === 'Demo'"> <Demo /> </body> </div>`, name: 'app', data() { return { displayedComponent: 'Home', team: [ { name: 'Michael Gower', email: 'gowermikey@gmail.com', picture: '/assets/Mikey.jpg', about: 'N/A', github: 'https://github.com/mggower', linkdIn: 'N/A', }, { name: 'Jordan Grubb', email: 'ImJordanGrubb@gmail.com', picture: '/assets/Jordan.jpg', about: 'N/A', github: 'https://github.com/jgrubb16', linkdIn: 'https://www.linkedin.com/in/j-grubb', }, { name: 'Kyle Jurassic', email: 'kjuresich@gmail.com', picture: '/assets/Kyle.jpg', about: 'N/A', github: 'http://github.com/kjurassic', linkdIn: 'http://linkedin.com/in/kyle-juresich/', }, { name: 'Andrew Rehrig', email: 'arehrig@gmail.com', picture: '/assets/Andrew.jpg', about: 'N/A', github: 'https://github.com/andrew-rehrig', linkdIn: 'https://www.linkedin.com/in/andrew-rehrig/', }, ], }; }, methods: { handelClick: function (event) { this.displayedComponent = event; console.log(this.displayedComponent); }, }, components: { Home, Team, Docs, Demo, },});

App.$mount("#app");
export default App;
