/* eslint-disable */
// prettier-ignore
import Vue from 'https://cdn.jsdelivr.net/npm/vue@2.6.12/dist/vue.esm.browser.js';

const IndividualComment = Vue.component("individual-comment", {template: ` <div> <li> <img class="post-img" :src="commentpost.authorImg" /> <small>{{ commentpost.author }}</small> <p class="post-comment">"{{ commentpost.text }}"</p> </li> </div>`, name: 'individual-comment', props: ["commentpost"],});
const Destinations = Vue.component("destinations", {template: ` <div class="place"> <img :src="location.img" width="235" height="300" /> <slot></slot> <p>{{ location.desc }}</p> </div>`, props: ['location'],});
const LilOrange = Vue.component("lil-orange", {template: ` <div id="lilorange"> <h1>i'm just a clementine</h1> </div>`, data() { return { color: 'orange', }; },});
const Red = Vue.component("red", {template: `<div id="red"> <h1>Andrew</h1> <a href="https://imgbb.com/" ><img src="https://i.ibb.co/cxPPLvy/andrew.png" alt="andrew" border="0" /></a> <p> Andrew is a classically trained flutist. He's a boss ass bitch who don't &nbsp; take no shit </p></div>`,name: 'red',data() { return { color: 'red', };},components: { LilOrange },});
const Green = Vue.component("green", {template: `<div id="green"> <h1>Mikey</h1> <a href="https://imgbb.com/" ><img src="https://i.ibb.co/Lz6jw4b/mikey.png" alt="mikey" border="0" /></a> <p> Mikey is a certified Sommolier. That means he knows a lot more about wine &nbsp;than you do. Also Sake. </p></div>`,name: 'green',data() { return { color: 'green', };},});
const Orange = Vue.component("orange", {template: ` <div id="orange"> <h1>Jordan</h1> <a href="https://imgbb.com/" ><img src="https://i.ibb.co/m46njhp/jordan.png" alt="jordan" border="0" /></a> <p>Jordan has worked on Broadway! So, yes, he has much sass!</p> </div>`, name: 'orange', data() { return { color: 'orange', }; }, components: { LilOrange, },});
const Purple = Vue.component("purple", {template: `<div id="purple"> <h1>Kyle</h1> <a href="https://imgbb.com/" ><img src="https://i.ibb.co/6rxv4gC/kyle.png" alt="kyle" border="0" /></a> <p>Kyle (aka Grandpa Kyle) is here to party</p></div>`,name: 'purple',data() { return { color: 'purple', };},components: { LilOrange },});
const Travel = Vue.component("travel", {template: ` <div id="travel"> <h1>Your Upcoming Destinations</h1> <div class="location-contain"> <div class="locations" v-for="location in locations" :key="location.desc"> <destinations :location="location"> <h2>{{ location.name }}</h2> </destinations> </div> </div> </div>`, name: 'travel', components: { Destinations, }, data() { return { locations: [ { name: 'moscow', img: 'https://s3-us-west-2.amazonaws.com/s.cdpn.io/28963/moscow.svg', desc: `Moscow is the capital and most populous city of Russia, with 13.2 million residents within the city limits and 17.8 million within the urban area. Moscow has the status of a Russian federal city.`, }, { name: 'paris', img: 'https://s3-us-west-2.amazonaws.com/s.cdpn.io/28963/paris1.svg', desc: `Paris is the capital and most populous city of France. By the 17th century, Paris was one of Europe's major centres of finance, commerce, fashion, science, and the arts, and it retains that position still today.`, }, { name: 'rome', img: 'https://s3-us-west-2.amazonaws.com/s.cdpn.io/28963/rome.svg', desc: `Rome's history spans more than 2,500 years. While Roman mythology dates the founding of Rome at around 753 BC, the site has been inhabited for much longer, making it one of the oldest continuously occupied sites in Europe.`, }, { name: 'paris', img: 'https://s3-us-west-2.amazonaws.com/s.cdpn.io/28963/paris2.svg', desc: `By the end of the 12th century, Paris had become the political, economic, religious, and cultural capital of France. Maurice de Sully undertook the construction of the Notre Dame Cathedral at its eastern extremity.`, }, ], }; },});
const Lighthouse = Vue.component("lighthouse", {template: ` <div id="lighthouse"> <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/28963/vue-post-photo.jpg" class="main-photo" /> <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/28963/vue-main-profile.jpg" class="main-profile" /> <div class="main-info"> <span class="name">Julianne Delfina</span> <h3>"It's lovely after it rains"</h3> </div> <hr /> <ul> <individual-comment v-for="comment in allComments" :key="comment.key" :commentpost="comment" ></individual-comment> </ul> <input v-model="newComment" @keyup.enter="addComment" placeholder="Add a comment" /> </div>`, name: 'lighthouse', components: { IndividualComment, }, data() { return { newComment: '', allComments: [], count: 0, }; }, computed: { comments() { console.log('x'); }, }, methods: { addComment() { const post = { key: this.count, text: this.newComment, author: 'VNO TEAM', authorImg: 'https://i.ibb.co/1qLqhFv/vno-57.png', }; console.log(this.newComment); this.allComments = [...this.allComments, post]; this.newComment = ''; this.count += 1; }, },});
const App = new Vue({template: ` <div id="app"> <header class="header"> <img class="logo" src="https://svgshare.com/i/SNz.svg" alt="logo" /> <nav class="inner"> <button v-on:click="handelClick('green')">Mikey</button> <button v-on:click="handelClick('orange')">Jordan</button> <button v-on:click="handelClick('purple')">Kyle</button> <button v-on:click="handelClick('red')">Andrew</button> <button v-on:click="handelClick('travel')">Travel</button> <button v-on:click="handelClick('lighthouse')">Lighthouse</button> <a class="github" href="https://github.com/oslabs-beta/vno" target="_blank" ><button>Github</button> </a> </nav> </header> <body v-if="displayedComponent === 'red'"> <Red /> </body> <body v-else-if="displayedComponent === 'green'"> <Green /> </body> <body v-else-if="displayedComponent === 'orange'"> <Orange /> </body> <body v-else-if="displayedComponent === 'purple'"> <Purple /> </body> <body v-else-if="displayedComponent === 'lighthouse'"> <Lighthouse /> </body> <body v-else-if="displayedComponent === 'travel'"> <Travel /> </body> <body v-else> <h1>Welcome to Your vno Project</h1> <p> For a guide on project customization,<br /> check out out GitHub repo at: <a href="https://github.com/oslabs-beta/vno" target="_blank" rel="noopener" >vno documentation</a > </p> <ul> <li> <a href="https://github.com/jgrubb16/vnocli" target="_blank" rel="noopener" >Open Source CLI Tool</a > </li> </ul> </body> </div>`, name: 'app', data() { return { displayedComponent: '', }; }, methods: { handelClick: function (event) { this.displayedComponent = event; console.log(this.displayedComponent); }, }, components: { Red, Green, Orange, Purple, LilOrange, Travel, Lighthouse, },});

App.$mount("#app");
export default App;
